### ISSUE TITLE
Some words with initial upper case are underlined *and* suggested

### ISSUE THREAD

**Issue by snomos** [divvun/hfst-ospell-js#4]
See attached screenshot:

![sijda](https://cloud.githubusercontent.com/assets/1255285/19436363/53f9c070-9478-11e6-9763-b306c9808c8e.png)

"sijdâ" is not underlined, "Sijdâ" is, and gets as its first suggestion itself.

Initially it seemed that the core difference was the occurrence of accented characters, but that seems not to be the case:

Underlined words:

> Kielâpargee Sijdâ Taiđuu Sämmilâš Seminaar Keejâ

Ununderlined words:

> Suomâ Sämitigge Sämiarkkâdâh Min Sämikulttuurkuávdáš Sajosist Anarist

Lowercase versions of these words (those that are not names) are accepted.

To reproduce, paste the following text into the editor area of http://divvun.no/korrektur/speller-demo.html and set the language to Inari Sámi (upper left button in the Language dialog box):

> Suomâ Sämitigge ocá projektân nuorttâsämikielâ kielâpargee sajasii ááigán 19.10.2016–14.8.2017. Kielâpargee pargoid kuleh kielâtipšom, kielâovdedem, terminologiapargo, normâdem, sehe tieđettem- já ravvimpargo. Sämitigge, Sijdâ, ja sijdâ ja Sijdâ  Sämiarkkâdâh já Taiđuu ovdedemkuávdáš uárnejeh Min árbi – Sämmilâš ja Sämmilâš kulttuurärbi seminaar koskoho 5.10.2016 Sämikulttuurkuávdáš Sajosist Anarist. Seminaar lii ávus puohháid. Keejâ ohjelm tást.  Keejâ ja keejâ ja

**Comment by snomos** [comment]
The original bug report was filed here: http://giellatekno.uit.no/bugzilla/show_bug.cgi?id=2227.

**Comment by bbqsrc** [comment]
Can you confirm this is fixed?

**Comment by snomos** [comment]
I can confirm. Repeating the steps above gives no unexpected red underlines.
